apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-server
        image: auth:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: auth-port
        resources:
          requests:
            cpu: "30m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: flowent-secrets
                key: MONGO_URI
                optional: true
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: flowent-secrets
                key: JWT_SECRET
                optional: true
          - name: GOOGLE_OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: flowent-secrets
                key: GOOGLE_OAUTH_CLIENT_ID
                optional: true
          - name: GOOGLE_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: flowent-secrets
                key: GOOGLE_OAUTH_CLIENT_SECRET
                optional: true
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: flowent-secrets
                key: REDIS_URL
                optional: true
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 3000
          initialDelaySeconds: 60
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/readyz
            port: 3000
          initialDelaySeconds: 20
          timeoutSeconds: 10
